[project]
name = "health-backend"
version = "0.1.0"
description = "Health backend"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.3",
    "alembic>=1.18.3",
    "alembic-postgresql-enum>=1.9.0",
    "argon2-cffi>=25.1.0",
    "asyncpg>=0.31.0",
    "click>=8.3.1",
    "dishka>=1.7.2",
    "fastapi[standard]>=0.124.4",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "pyjwt>=2.11.0",
    "pytest>=9.0.2",
    "sqlalchemy[asyncio]>=2.0.46",
]
authors = [
  {name = "sazsu"},
]

[project.scripts]
health = "health_backend.main.cli:cli"

[build-system]
requires = ["uv_build>=0.9.17,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.14.9",
]

[tool.ruff]
line-length = 100
exclude = [
  "./src/health_backend/adapters/persistence/db/alembic",
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "A002", # Function argument `id` is shadowing a Python builtin
    "D",
    "TC001",
    "TC002",
    "TC003",
    "TC006",
    "Q000",
    "Q003",
    "COM812",
    "EM101",
    "S106", # Possible hardcoded password assigned to argument: "password"
    "RET504",
    "S101", # Use of `assert` detected
    "FBT001", # Boolean positional arg in function definition
    "RUF001", # String contains ambiguous `е` (CYRILLIC SMALL LETTER IE). Did you mean `e` (LATIN SMALL LETTER E)?
    "FIX002", # Line contains TODO, consider resolving the issue
    "TD002", # Missing author in TODO; try: `# TODO(<author_name>): ...` or `# TODO @<author_name>: ...`
    "TD003", # Missing issue link on the line following this TODO
    "ANN401",
]

[tool.ty.src]
exclude = [
  "./alembic",
]
