"""make email unique

Revision ID: 05a787a7853b
Revises: 2120df0d90d5
Create Date: 2026-02-08 23:24:35.438210

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '05a787a7853b'
down_revision: Union[str, Sequence[str], None] = '2120df0d90d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'doctor', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor', type_='unique')  # ty: ignore
    # ### end Alembic commands ###
