"""add doctor, patient

Revision ID: 2120df0d90d5
Revises:
Create Date: 2026-02-08 23:13:33.125220

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from health_backend.adapters.persistence.db.common.types import EmailType, NameType
from health_backend.adapters.persistence.db.recommendation.table import PatientHistoryType

# revision identifiers, used by Alembic.
revision: str = '2120df0d90d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'doctor',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', NameType(), nullable=False),
        sa.Column('email', EmailType(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'patient',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', NameType(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'recommendation',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('patient_history', PatientHistoryType(), nullable=False),
        sa.Column('systolic_blood_pressure_min', sa.Float(), nullable=False),
        sa.Column('systolic_blood_pressure_max', sa.Float(), nullable=False),
        sa.Column('diastolic_blood_pressure_min', sa.Float(), nullable=False),
        sa.Column('diastolic_blood_pressure_max', sa.Float(), nullable=False),
        sa.Column('temperature_celsius_min', sa.Float(), nullable=False),
        sa.Column('temperature_celsius_max', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['patient_id'],
            ['patient.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation')
    op.drop_table('patient')
    op.drop_table('doctor')
    # ### end Alembic commands ###
