"""non future date type

Revision ID: 68f339d596d7
Revises: a4cb726f5c0a
Create Date: 2026-03-28 23:06:30.028745

"""
from typing import Sequence, Union
import health_backend.adapters.persistence.db.common.types

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68f339d596d7'
down_revision: Union[str, Sequence[str], None] = 'a4cb726f5c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'birth_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=health_backend.adapters.persistence.db.common.types.NonFutureDateType(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'birth_date',
               existing_type=health_backend.adapters.persistence.db.common.types.NonFutureDateType(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
