"""no timezone in birth_date

Revision ID: fbf8e9e7ac1b
Revises: ff67be46e448
Create Date: 2026-02-09 22:33:32.486345

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fbf8e9e7ac1b'
down_revision: Union[str, Sequence[str], None] = 'ff67be46e448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
