"""add birth_date, gender to patient

Revision ID: ff67be46e448
Revises: 9ee337212b32
Create Date: 2026-02-09 22:31:24.828739

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff67be46e448'
down_revision: Union[str, Sequence[str], None] = '9ee337212b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MALE', 'FEMALE', name='gender_enum').create(op.get_bind())
    op.add_column('patient', sa.Column('birth_date', sa.DateTime(), nullable=False))
    op.add_column('patient', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'gender')
    op.drop_column('patient', 'birth_date')
    sa.Enum('MALE', 'FEMALE', name='gender_enum').drop(op.get_bind())
    # ### end Alembic commands ###
