"""add is_active to patient

Revision ID: a4cb726f5c0a
Revises: fbf8e9e7ac1b
Create Date: 2026-02-09 23:59:57.750477

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a4cb726f5c0a'
down_revision: Union[str, Sequence[str], None] = 'fbf8e9e7ac1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute('UPDATE patient SET is_active = true WHERE is_active IS NULL')
    op.alter_column('patient', 'is_active', nullable=False)
    op.alter_column(
        'patient',
        'birth_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'patient',
        'birth_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_column('patient', 'is_active')
    # ### end Alembic commands ###
