"""add recommendation

Revision ID: ca7fd045ee76
Revises: 05a787a7853b
Create Date: 2026-02-08 23:33:05.093443

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from health_backend.adapters.persistence.db.recommendation.table import ThresholdsType

# revision identifiers, used by Alembic.
revision: str = 'ca7fd045ee76'
down_revision: Union[str, Sequence[str], None] = '05a787a7853b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendation', sa.Column('thresholds', ThresholdsType(), nullable=False))
    op.drop_column('recommendation', 'temperature_celsius_max')
    op.drop_column('recommendation', 'diastolic_blood_pressure_max')
    op.drop_column('recommendation', 'temperature_celsius_min')
    op.drop_column('recommendation', 'diastolic_blood_pressure_min')
    op.drop_column('recommendation', 'systolic_blood_pressure_max')
    op.drop_column('recommendation', 'systolic_blood_pressure_min')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'recommendation',
        sa.Column(
            'systolic_blood_pressure_min',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'recommendation',
        sa.Column(
            'systolic_blood_pressure_max',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'recommendation',
        sa.Column(
            'diastolic_blood_pressure_min',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'recommendation',
        sa.Column(
            'temperature_celsius_min',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'recommendation',
        sa.Column(
            'diastolic_blood_pressure_max',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'recommendation',
        sa.Column(
            'temperature_celsius_max',
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column('recommendation', 'thresholds')
    # ### end Alembic commands ###
