class DomainError(Exception): ...


class EmptyPatientHistoryError(DomainError): ...


class EmptyNameError(DomainError): ...


class EmptyEmailError(DomainError): ...


class InactiveError(DomainError): ...


class InvalidEmailError(DomainError): ...
