class UnauthorizedError(Exception): ...


class EmailAlreadyInUse(Exception): ...


class DepartmentDoesNotExist(Exception): ...


class ForbiddenActionError(Exception): ...


class UserDoesNotExist(Exception): ...
class UserIsNotDoctor(Exception): ...
class WrongUserStatus(Exception): ...
