name: CI/CD
on: [push]

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Lint
        run: |
          uv sync --all-groups
          uv run ruff check
          # uvx ty check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run unit tests
        run: |
          uv sync --all-groups
          uv run pytest ./tests/unit
      - name: Run end-to-end tests
        run: |
          uv sync --all-groups
          uv run pytest ./tests/e2e

  push:
    name: Build and push docker image to registry
    needs: [lint, test]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v6
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ vars.IMAGE_NAME }}
      - name: Login to registry
        run: |
          echo ${{ secrets.CR_PAT }} | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
      - name: Push to registry
        run: |
          IMAGE_ID=$REGISTRY/${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}
          VERSION=${{ github.sha }}
          docker tag ${{ vars.IMAGE_NAME }} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
